### ISSUE TITLE
Come alive, v5!

### ISSUE THREAD

**Issue by dpinn** [annaghi/dnd-list#14]
Hi Anna,

I'm eagerly awaiting v5, since I'd like to perform operations only after a drop has been performed. How close are we to publishing v5?

David

**Comment by annaghi** [comment]
Hi David,

Nice to hear that!
I am still working on v5. It will support much more features, please be patient for a couple of weeks.

Thanks,
Anna

**Comment by dpinn** [comment]
Oooh, I'm seeing lots of commits. Go Anna, go!

**Comment by annaghi** [comment]
:smile: 

The v5 will be official on Monday.

**Comment by dpinn** [comment]
Woot! I see that you've tagged with '5.0.0'. Thanks very much for your efforts.

**Comment by annaghi** [comment]
Yes, finally. You're welcome!
I shouldn't have to set the release day, there is always something to deal with.
