### ISSUE TITLE
How do i dnd on tree list?

### ISSUE THREAD

**Issue by afidegnum** [annaghi/dnd-list#63]
Hi, 
I am very excited coming across this package, it's well crafted, as reading the documentation i m a bit stuck on drag-and-drop on tree of list or elements (nested lists).

can you please share some insight about it ?

**Comment by annaghi** [comment]
I am glad you like the package. There is no support for nested lists yet, you cannot use this package for them.

Although I have plans for implementing that, I do not know when I have time for that.

**Comment by annaghi** [comment]
Others:

[React Sortly](https://lytc.github.io/react-sortly/#/)
[react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd)
[reorderables](https://pub.dev/packages/reorderables)

**Comment by annaghi** [comment]
Hi @afidegnum ,
have you seen [this post](https://blog.noredink.com/post/186724971283/drag-drop-without-draggables-dropzones) and [Ellie example](https://ellie-app.com/6gbMfDjCnH4a1)? Perhaps it can be useful for you.

**Comment by afidegnum** [comment]
thanks a lot, they are very useful posts, it will will help a lot in what i am trying to build. I will keep you updated

**Comment by annaghi** [comment]
Closing this because the `dnd-list` package will not support trees. It should be a matter of another package.
