### ISSUE TITLE
Compiling with create-elm-app gives error with import:

### ISSUE THREAD

**Issue by 3digitdev** [annaghi/dnd-list#69]
I made a new project with `create-elm-app`, and did a near copy-paste of the examples in your documentation, but I get this error in my code:

![image](https://user-images.githubusercontent.com/52093780/71611842-ea3e6080-2b61-11ea-8177-721cb8dfc1b1.png)

**Comment by 3digitdev** [comment]
Closing this issue -- i did a manual new project using just `elm init` and copy/pasted your example and it worked perfectly.  I have absolutely no idea why `create-elm-app` was failing.  Might be still looking into, given the popularity of it...

**Comment by annaghi** [comment]
Thank you for letting me know about it.

I will try how `create-elm-app` works and will investigate what is going on.
